// <auto-generated />
using System;
using Account.Infrastructure.MySql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Account.Infrastructure.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20190718230424_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Account.Domain.Entities.AccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountID");

                    b.Property<string>("AccountNumber");

                    b.Property<string>("AgencyNumber");

                    b.Property<decimal>("Balance");

                    b.Property<bool>("Bloqued");

                    b.Property<Guid>("ClientID");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("AccountEntities");
                });

            modelBuilder.Entity("Account.Domain.Entities.ClientEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<Guid>("ClientID");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Name");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("Id");

                    b.ToTable("ClientEntities");
                });

            modelBuilder.Entity("Account.Domain.Entities.TransferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AccountIDfrom");

                    b.Property<Guid>("AccountIDto");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("TypePay");

                    b.Property<int>("TypeTransaction");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<decimal>("value");

                    b.HasKey("Id");

                    b.ToTable("TransferEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
